// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Icon:ic:baselineArrowRightAlt': typeof import('~icons/ic/baseline-arrow-right-alt')['default']
    'IconBi:exclamationCircleFill': typeof import('~icons/bi/exclamation-circle-fill')['default']
    'IconClarity:pencilLine': typeof import('~icons/clarity/pencil-line')['default']
    'IconClarity:timesCircleSolid': typeof import('~icons/clarity/times-circle-solid')['default']
    'IconClarity:timesLine': typeof import('~icons/clarity/times-line')['default']
    'IconFa6Brands:github': typeof import('~icons/fa6-brands/github')['default']
    'IconFa6Brands:instagam': typeof import('~icons/fa6-brands/instagam')['default']
    'IconFa6Brands:instagram': typeof import('~icons/fa6-brands/instagram')['default']
    'IconFa6Brands:linkedinIn': typeof import('~icons/fa6-brands/linkedin-in')['default']
    'IconFa6Brands:twitte': typeof import('~icons/fa6-brands/twitte')['default']
    'IconFa6Brands:twitter': typeof import('~icons/fa6-brands/twitter')['default']
    'IconIc:baselineContentCopy': typeof import('~icons/ic/baseline-content-copy')['default']
    'IconLa:language': typeof import('~icons/la/language')['default']
    'IconMaterialSymbols:contentCopyOutline': typeof import('~icons/material-symbols/content-copy-outline')['default']
    'IconMdi:checkCircle': typeof import('~icons/mdi/check-circle')['default']
    'IconMdi:githubFace': typeof import('~icons/mdi/github-face')['default']
    'IconUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'IconUil:apps': typeof import('~icons/uil/apps')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
